# Enable Bluetooth Host Support
# CONFIG_BT=y

# Tell Zephyr we are using an external HCI Controller over UART
CONFIG_BT_HCI=y
CONFIG_GPIO=y
CONFIG_BT=y
# CONFIG_BT_HCI_RAW=n

# CRITICAL: Disable the internal Zephyr Link Layer Controller
CONFIG_BT_LL_SW_SPLIT=n

# Disable UART Hardware Flow Control since we are only using RX/TX pins (no RTS/CTS)
# CONFIG_BT_HCI_ACL_FLOW_CONTROL=n