# enables the new gen usb stack
CONFIG_USB_DEVICE_STACK_NEXT=y

# enables the console subsystem where the stdout will be redirected
CONFIG_STDOUT_CONSOLE=y

# enables serial/uart subsystem 
CONFIG_SERIAL=y

# for setting DTR, DSR, DCD, baud rate. uart_line_ctrl_get(dev, UART_LINE_CTRL_DTR, &dtr) which gives access to zephyr/drivers/uart.h
# important for 	k_msleep(100);
CONFIG_UART_LINE_CTRL=y

# makes the cdc acm class instance not auto initialize (usbd_enable()), instead
# you do it manually in the code
CONFIG_CDC_ACM_SERIAL_INITIALIZE_AT_BOOT=n

#enables log
CONFIG_LOG=y


CONFIG_LOG_MODE_IMMEDIATE=y

# limits log priority of usbd to err
CONFIG_USBD_LOG_LEVEL_ERR=y

# Same idea, but for the UDC driver layer (the hardware controller driver itself) — errors only.
CONFIG_UDC_DRIVER_LOG_LEVEL_ERR=y


CONFIG_USBD_CDC_ACM_LOG_LEVEL_OFF=y
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_WARN_EXPERIMENTAL=y
CONFIG_SAMPLE_USBD_PID=0x0001
CONFIG_SAMPLE_USBD_PRODUCT="USBD CDC ACM sample"



# bluetooth hci uart setup
CONFIG_BT=y

# Directs Zephyr to route HCI packets over the physical UART peripheral 
# selected by your 'zephyr,bt-hci' chosen property in the device tree
# cna't configure it CONFIG_BT_UART=y


#CONFIG_BT_H4=y


# Allocates the background thread stack size for handling outgoing HCI packets
#CONFIG_BT_HCI_TX_STACK_SIZE=512

#CONFIG_BT_HCI=y
#CONFIG_BT_LL_SW_SPLIT=n #unsure
#CONFIG_BT_DEVICE_NAME="gateway"




#CONFIG_BT_CTLR=n